//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveFlip.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DriveFlip.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string AboutClose {
            get {
                return ResourceManager.GetString("AboutClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveFlip surfaces what matters — health data, risk flags, and actionable intelligence — so you can price confidently, wipe efficiently, and ship drives that don&apos;t come back..
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Check &amp; Drive Prep.
        /// </summary>
        public static string AboutSubtitle {
            get {
                return ResourceManager.GetString("AboutSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pragmatic Peace of Mind.
        /// </summary>
        public static string AboutTagline {
            get {
                return ResourceManager.GetString("AboutTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveFlip.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate License.
        /// </summary>
        public static string ActivateLicense {
            get {
                return ResourceManager.GetString("ActivateLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activating....
        /// </summary>
        public static string Activating {
            get {
                return ResourceManager.GetString("Activating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Time for Slow. Random Wipe and Go..
        /// </summary>
        public static string AppSubtitle {
            get {
                return ResourceManager.GetString("AppSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAIL.
        /// </summary>
        public static string BadgeFail {
            get {
                return ResourceManager.GetString("BadgeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASS.
        /// </summary>
        public static string BadgePass {
            get {
                return ResourceManager.GetString("BadgePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYS.
        /// </summary>
        public static string BadgeSys {
            get {
                return ResourceManager.GetString("BadgeSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check &amp; Wipe.
        /// </summary>
        public static string CheckAndWipe {
            get {
                return ResourceManager.GetString("CheckAndWipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-phase operation: surface check first, then wipe if check passes..
        /// </summary>
        public static string CheckAndWipeDesc {
            get {
                return ResourceManager.GetString("CheckAndWipeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Info.
        /// </summary>
        public static string CopyInfo {
            get {
                return ResourceManager.GetString("CopyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} drive(s) complete.
        /// </summary>
        public static string DashboardDrivesComplete {
            get {
                return ResourceManager.GetString("DashboardDrivesComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECK &amp; WIPE — Two-phase operation
        ///
        ///1. Surface check ({0} min per drive)
        ///2. {1} (if check passes)
        ///
        ///Drives:
        ///{2}
        ///
        ///If the surface check finds errors, you&apos;ll be asked whether to continue.
        ///
        ///Proceed?.
        /// </summary>
        public static string DialogCheckWipeConfirm {
            get {
                return ResourceManager.GetString("DialogCheckWipeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Check &amp; Wipe.
        /// </summary>
        public static string DialogConfirmCheckWipe {
            get {
                return ResourceManager.GetString("DialogConfirmCheckWipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Surface Check.
        /// </summary>
        public static string DialogConfirmSurfaceCheck {
            get {
                return ResourceManager.GetString("DialogConfirmSurfaceCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Wipe.
        /// </summary>
        public static string DialogConfirmWipe {
            get {
                return ResourceManager.GetString("DialogConfirmWipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Confirmation.
        /// </summary>
        public static string DialogFinalConfirmation {
            get {
                return ResourceManager.GetString("DialogFinalConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues Found — Continue Wipe?.
        /// </summary>
        public static string DialogIssuesFoundContinue {
            get {
                return ResourceManager.GetString("DialogIssuesFoundContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface check found issues on {0} drive(s):
        ///
        ///{1}
        ///
        ///Do you still want to proceed with wiping ALL selected drives?.
        /// </summary>
        public static string DialogIssuesFoundMessage {
            get {
                return ResourceManager.GetString("DialogIssuesFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run a {0}-minute surface check on {1} drive(s)?
        ///
        ///{2}
        ///
        ///This is read-only and will not modify any data..
        /// </summary>
        public static string DialogSurfaceCheckConfirm {
            get {
                return ResourceManager.GetString("DialogSurfaceCheckConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following system drive(s) were excluded for safety:
        ///
        ///{0}.
        /// </summary>
        public static string DialogSystemDriveExcluded {
            get {
                return ResourceManager.GetString("DialogSystemDriveExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Drive Protected.
        /// </summary>
        public static string DialogSystemDriveProtected {
            get {
                return ResourceManager.GetString("DialogSystemDriveProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Verification pass will run after wiping..
        /// </summary>
        public static string DialogVerifyWillRun {
            get {
                return ResourceManager.GetString("DialogVerifyWillRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL DATA WILL BE PERMANENTLY DESTROYED
        ///
        ///Mode: {0}
        ///Fill: {1}
        ///Passes: {2}{3}
        ///
        ///Drives to wipe:
        ///{4}
        ///
        ///This action CANNOT be undone. Continue?.
        /// </summary>
        public static string DialogWipeConfirm {
            get {
                return ResourceManager.GetString("DialogWipeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINAL WARNING
        ///
        ///Are you absolutely sure you want to permanently erase {0} drive(s)?
        ///
        ///Click YES only if you are certain..
        /// </summary>
        public static string DialogWipeFinalConfirm {
            get {
                return ResourceManager.GetString("DialogWipeFinalConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive Info.
        /// </summary>
        public static string DriveInfo {
            get {
                return ResourceManager.GetString("DriveInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No partitions.
        /// </summary>
        public static string DriveNoPartitions {
            get {
                return ResourceManager.GetString("DriveNoPartitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No volumes.
        /// </summary>
        public static string DriveNoVolumes {
            get {
                return ResourceManager.GetString("DriveNoVolumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 partition.
        /// </summary>
        public static string DrivePartitionSingular {
            get {
                return ResourceManager.GetString("DrivePartitionSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} partitions.
        /// </summary>
        public static string DrivePartitionsPlural {
            get {
                return ResourceManager.GetString("DrivePartitionsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drives.
        /// </summary>
        public static string Drives {
            get {
                return ResourceManager.GetString("Drives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to used.
        /// </summary>
        public static string DriveUsedSuffix {
            get {
                return ResourceManager.GetString("DriveUsedSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump Raw Data.
        /// </summary>
        public static string DumpRawData {
            get {
                return ResourceManager.GetString("DumpRawData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint URL.
        /// </summary>
        public static string EndpointUrl {
            get {
                return ResourceManager.GetString("EndpointUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string EngineComplete {
            get {
                return ResourceManager.GetString("EngineComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head wipe (Pass {0}/{1}).
        /// </summary>
        public static string EngineHeadWipe {
            get {
                return ResourceManager.GetString("EngineHeadWipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open Disk {0} for reading (Win32 error {1}). Run as Administrator..
        /// </summary>
        public static string EngineOpenReadError {
            get {
                return ResourceManager.GetString("EngineOpenReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open Disk {0} for writing (Win32 error {1}). Run as Administrator..
        /// </summary>
        public static string EngineOpenWriteError {
            get {
                return ResourceManager.GetString("EngineOpenWriteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling... {0} sectors checked.
        /// </summary>
        public static string EngineSampling {
            get {
                return ResourceManager.GetString("EngineSampling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scatter wipe (Pass {0}/{1})... {2}%.
        /// </summary>
        public static string EngineScatterWipe {
            get {
                return ResourceManager.GetString("EngineScatterWipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart wipe complete.
        /// </summary>
        public static string EngineSmartWipeComplete {
            get {
                return ResourceManager.GetString("EngineSmartWipeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tail wipe (Pass {0}/{1}).
        /// </summary>
        public static string EngineTailWipe {
            get {
                return ResourceManager.GetString("EngineTailWipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying... {0}%.
        /// </summary>
        public static string EngineVerifying {
            get {
                return ResourceManager.GetString("EngineVerifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe complete.
        /// </summary>
        public static string EngineWipeComplete {
            get {
                return ResourceManager.GetString("EngineWipeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiping... {0}%.
        /// </summary>
        public static string EngineWiping {
            get {
                return ResourceManager.GetString("EngineWiping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiping (Pass {0}/{1})... {2}%.
        /// </summary>
        public static string EngineWipingPass {
            get {
                return ResourceManager.GetString("EngineWipingPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External only.
        /// </summary>
        public static string ExternalOnly {
            get {
                return ResourceManager.GetString("ExternalOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string FieldCapacity {
            get {
                return ResourceManager.GetString("FieldCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string FieldFeatures {
            get {
                return ResourceManager.GetString("FieldFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware.
        /// </summary>
        public static string FieldFirmware {
            get {
                return ResourceManager.GetString("FieldFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string FieldHealth {
            get {
                return ResourceManager.GetString("FieldHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        public static string FieldInterface {
            get {
                return ResourceManager.GetString("FieldInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacture Date.
        /// </summary>
        public static string FieldManufactureDate {
            get {
                return ResourceManager.GetString("FieldManufactureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string FieldManufacturer {
            get {
                return ResourceManager.GetString("FieldManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Type.
        /// </summary>
        public static string FieldMediaType {
            get {
                return ResourceManager.GetString("FieldMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string FieldModel {
            get {
                return ResourceManager.GetString("FieldModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partition Style.
        /// </summary>
        public static string FieldPartitionStyle {
            get {
                return ResourceManager.GetString("FieldPartitionStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Number.
        /// </summary>
        public static string FieldPartNumber {
            get {
                return ResourceManager.GetString("FieldPartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power-On Hours.
        /// </summary>
        public static string FieldPowerOnHours {
            get {
                return ResourceManager.GetString("FieldPowerOnHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Errors.
        /// </summary>
        public static string FieldReadErrors {
            get {
                return ResourceManager.GetString("FieldReadErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Size.
        /// </summary>
        public static string FieldSectorSize {
            get {
                return ResourceManager.GetString("FieldSectorSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string FieldSerialNumber {
            get {
                return ResourceManager.GetString("FieldSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spindle Speed.
        /// </summary>
        public static string FieldSpindleSpeed {
            get {
                return ResourceManager.GetString("FieldSpindleSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSD Wear.
        /// </summary>
        public static string FieldSsdWear {
            get {
                return ResourceManager.GetString("FieldSsdWear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string FieldStatus {
            get {
                return ResourceManager.GetString("FieldStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string FieldTemperature {
            get {
                return ResourceManager.GetString("FieldTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Mode.
        /// </summary>
        public static string FieldTransferMode {
            get {
                return ResourceManager.GetString("FieldTransferMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Errors.
        /// </summary>
        public static string FieldWriteErrors {
            get {
                return ResourceManager.GetString("FieldWriteErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string FormatDisabled {
            get {
                return ResourceManager.GetString("FormatDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string FormatEnabled {
            get {
                return ResourceManager.GetString("FormatEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string FormatNo {
            get {
                return ResourceManager.GetString("FormatNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string FormatNotAvailable {
            get {
                return ResourceManager.GetString("FormatNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 512e (512 / 4096).
        /// </summary>
        public static string FormatSector512e {
            get {
                return ResourceManager.GetString("FormatSector512e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSD (no spindle).
        /// </summary>
        public static string FormatSsdNoSpindle {
            get {
                return ResourceManager.GetString("FormatSsdNoSpindle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string FormatYes {
            get {
                return ResourceManager.GetString("FormatYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get SMART Data.
        /// </summary>
        public static string GetSmartData {
            get {
                return ResourceManager.GetString("GetSmartData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Summary.
        /// </summary>
        public static string HealthSummary {
            get {
                return ResourceManager.GetString("HealthSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON files (*.json)|*.json.
        /// </summary>
        public static string JsonFilter {
            get {
                return ResourceManager.GetString("JsonFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Type.
        /// </summary>
        public static string LabelBusType {
            get {
                return ResourceManager.GetString("LabelBusType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string LabelCapacity {
            get {
                return ResourceManager.GetString("LabelCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string LabelDataPresence {
            get {
                return ResourceManager.GetString("LabelDataPresence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string LabelErrors {
            get {
                return ResourceManager.GetString("LabelErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string LabelFeatures {
            get {
                return ResourceManager.GetString("LabelFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware.
        /// </summary>
        public static string LabelFirmware {
            get {
                return ResourceManager.GetString("LabelFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flush Latency Max.
        /// </summary>
        public static string LabelFlushLatencyMax {
            get {
                return ResourceManager.GetString("LabelFlushLatencyMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string LabelHealthStatus {
            get {
                return ResourceManager.GetString("LabelHealthStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        public static string LabelInterface {
            get {
                return ResourceManager.GetString("LabelInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load/Unload Cycles.
        /// </summary>
        public static string LabelLoadUnloadCycles {
            get {
                return ResourceManager.GetString("LabelLoadUnloadCycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string LabelManufacturer {
            get {
                return ResourceManager.GetString("LabelManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Type.
        /// </summary>
        public static string LabelMediaType {
            get {
                return ResourceManager.GetString("LabelMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mfg. Date.
        /// </summary>
        public static string LabelMfgDate {
            get {
                return ResourceManager.GetString("LabelMfgDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string LabelModel {
            get {
                return ResourceManager.GetString("LabelModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Spare.
        /// </summary>
        public static string LabelNvmeAvailableSpare {
            get {
                return ResourceManager.GetString("LabelNvmeAvailableSpare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller Busy.
        /// </summary>
        public static string LabelNvmeBusyTime {
            get {
                return ResourceManager.GetString("LabelNvmeBusyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Read.
        /// </summary>
        public static string LabelNvmeDataRead {
            get {
                return ResourceManager.GetString("LabelNvmeDataRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Written.
        /// </summary>
        public static string LabelNvmeDataWritten {
            get {
                return ResourceManager.GetString("LabelNvmeDataWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Errors.
        /// </summary>
        public static string LabelNvmeMediaErrors {
            get {
                return ResourceManager.GetString("LabelNvmeMediaErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent Used.
        /// </summary>
        public static string LabelNvmePercentUsed {
            get {
                return ResourceManager.GetString("LabelNvmePercentUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Cycles.
        /// </summary>
        public static string LabelNvmePowerCycles {
            get {
                return ResourceManager.GetString("LabelNvmePowerCycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsafe Shutdowns.
        /// </summary>
        public static string LabelNvmeUnsafeShutdowns {
            get {
                return ResourceManager.GetString("LabelNvmeUnsafeShutdowns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partitions.
        /// </summary>
        public static string LabelPartitions {
            get {
                return ResourceManager.GetString("LabelPartitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Number.
        /// </summary>
        public static string LabelPartNumber {
            get {
                return ResourceManager.GetString("LabelPartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power-On Hours.
        /// </summary>
        public static string LabelPowerOnHours {
            get {
                return ResourceManager.GetString("LabelPowerOnHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Protection.
        /// </summary>
        public static string LabelPowerProtection {
            get {
                return ResourceManager.GetString("LabelPowerProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Corrected.
        /// </summary>
        public static string LabelReadCorrected {
            get {
                return ResourceManager.GetString("LabelReadCorrected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Errors.
        /// </summary>
        public static string LabelReadErrors {
            get {
                return ResourceManager.GetString("LabelReadErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Latency Max.
        /// </summary>
        public static string LabelReadLatencyMax {
            get {
                return ResourceManager.GetString("LabelReadLatencyMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Uncorrected.
        /// </summary>
        public static string LabelReadUncorrected {
            get {
                return ResourceManager.GetString("LabelReadUncorrected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Size.
        /// </summary>
        public static string LabelSectorSize {
            get {
                return ResourceManager.GetString("LabelSectorSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string LabelSerial {
            get {
                return ResourceManager.GetString("LabelSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string LabelSpeed {
            get {
                return ResourceManager.GetString("LabelSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spindle Speed.
        /// </summary>
        public static string LabelSpindleSpeed {
            get {
                return ResourceManager.GetString("LabelSpindleSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSD Wear.
        /// </summary>
        public static string LabelSsdWear {
            get {
                return ResourceManager.GetString("LabelSsdWear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/Stop Cycles.
        /// </summary>
        public static string LabelStartStopCycles {
            get {
                return ResourceManager.GetString("LabelStartStopCycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string LabelTemperature {
            get {
                return ResourceManager.GetString("LabelTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Mode.
        /// </summary>
        public static string LabelTransferMode {
            get {
                return ResourceManager.GetString("LabelTransferMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB Bridge.
        /// </summary>
        public static string LabelUsbBridge {
            get {
                return ResourceManager.GetString("LabelUsbBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volumes.
        /// </summary>
        public static string LabelVolumes {
            get {
                return ResourceManager.GetString("LabelVolumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Cache.
        /// </summary>
        public static string LabelWriteCache {
            get {
                return ResourceManager.GetString("LabelWriteCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Corrected.
        /// </summary>
        public static string LabelWriteCorrected {
            get {
                return ResourceManager.GetString("LabelWriteCorrected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Errors.
        /// </summary>
        public static string LabelWriteErrors {
            get {
                return ResourceManager.GetString("LabelWriteErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Latency Max.
        /// </summary>
        public static string LabelWriteLatencyMax {
            get {
                return ResourceManager.GetString("LabelWriteLatencyMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Uncorrected.
        /// </summary>
        public static string LabelWriteUncorrected {
            get {
                return ResourceManager.GetString("LabelWriteUncorrected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License activated successfully!.
        /// </summary>
        public static string LicenseActivated {
            get {
                return ResourceManager.GetString("LicenseActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation failed: {0}.
        /// </summary>
        public static string LicenseActivationFailed {
            get {
                return ResourceManager.GetString("LicenseActivationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate a license to unlock surface check, wipe, and check &amp; wipe operations..
        /// </summary>
        public static string LicenseBannerText {
            get {
                return ResourceManager.GetString("LicenseBannerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition:.
        /// </summary>
        public static string LicenseEdition {
            get {
                return ResourceManager.GetString("LicenseEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires:.
        /// </summary>
        public static string LicenseExpires {
            get {
                return ResourceManager.GetString("LicenseExpires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This license key has expired..
        /// </summary>
        public static string LicenseKeyExpired {
            get {
                return ResourceManager.GetString("LicenseKeyExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid license key or signature verification failed..
        /// </summary>
        public static string LicenseKeyInvalid {
            get {
                return ResourceManager.GetString("LicenseKeyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Key.
        /// </summary>
        public static string LicenseKeyLabel {
            get {
                return ResourceManager.GetString("LicenseKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter license key....
        /// </summary>
        public static string LicenseKeyPlaceholder {
            get {
                return ResourceManager.GetString("LicenseKeyPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No license endpoint configured..
        /// </summary>
        public static string LicenseNoEndpoint {
            get {
                return ResourceManager.GetString("LicenseNoEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Required.
        /// </summary>
        public static string LicenseRequired {
            get {
                return ResourceManager.GetString("LicenseRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License revalidated..
        /// </summary>
        public static string LicenseRevalidated {
            get {
                return ResourceManager.GetString("LicenseRevalidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revalidating license....
        /// </summary>
        public static string LicenseRevalidating {
            get {
                return ResourceManager.GetString("LicenseRevalidating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revalidation error: {0}.
        /// </summary>
        public static string LicenseRevalidationError {
            get {
                return ResourceManager.GetString("LicenseRevalidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revalidation failed..
        /// </summary>
        public static string LicenseRevalidationFailed {
            get {
                return ResourceManager.GetString("LicenseRevalidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Settings.
        /// </summary>
        public static string LicenseSettingsLabel {
            get {
                return ResourceManager.GetString("LicenseSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensed (offline).
        /// </summary>
        public static string LicenseStatusCachedOffline {
            get {
                return ResourceManager.GetString("LicenseStatusCachedOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License expired.
        /// </summary>
        public static string LicenseStatusExpired {
            get {
                return ResourceManager.GetString("LicenseStatusExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid license.
        /// </summary>
        public static string LicenseStatusInvalid {
            get {
                return ResourceManager.GetString("LicenseStatusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensed.
        /// </summary>
        public static string LicenseStatusLicensed {
            get {
                return ResourceManager.GetString("LicenseStatusLicensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlicensed.
        /// </summary>
        public static string LicenseStatusUnlicensed {
            get {
                return ResourceManager.GetString("LicenseStatusUnlicensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensed to:.
        /// </summary>
        public static string LicenseTo {
            get {
                return ResourceManager.GetString("LicenseTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License required to use this feature.
        /// </summary>
        public static string LicenseTooltip {
            get {
                return ResourceManager.GetString("LicenseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many attempts. Try again in {0}m {1}s..
        /// </summary>
        public static string LicenseTooManyAttempts {
            get {
                return ResourceManager.GetString("LicenseTooManyAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many attempts. Try again in {0} minutes..
        /// </summary>
        public static string LicenseTooManyAttemptsMinutes {
            get {
                return ResourceManager.GetString("LicenseTooManyAttemptsMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ListingCancel {
            get {
                return ResourceManager.GetString("ListingCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string ListingCopy {
            get {
                return ResourceManager.GetString("ListingCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export for Listing.
        /// </summary>
        public static string ListingDialogTitle {
            get {
                return ResourceManager.GetString("ListingDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move field down.
        /// </summary>
        public static string ListingMoveDown {
            get {
                return ResourceManager.GetString("ListingMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move field up.
        /// </summary>
        public static string ListingMoveUp {
            get {
                return ResourceManager.GetString("ListingMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tested with DriveFlip · {0}.
        /// </summary>
        public static string ListingReportFooter {
            get {
                return ResourceManager.GetString("ListingReportFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRIVEFLIP DRIVE REPORT.
        /// </summary>
        public static string ListingReportHeader {
            get {
                return ResourceManager.GetString("ListingReportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Querying SMART data....
        /// </summary>
        public static string LoadingSmartData {
            get {
                return ResourceManager.GetString("LoadingSmartData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB/s.
        /// </summary>
        public static string MBps {
            get {
                return ResourceManager.GetString("MBps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVMe Health Log.
        /// </summary>
        public static string NvmeHealthLog {
            get {
                return ResourceManager.GetString("NvmeHealthLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full wipe.
        /// </summary>
        public static string PhaseFullWipe {
            get {
                return ResourceManager.GetString("PhaseFullWipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head wipe.
        /// </summary>
        public static string PhaseHeadWipe {
            get {
                return ResourceManager.GetString("PhaseHeadWipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scatter wipe.
        /// </summary>
        public static string PhaseScatterWipe {
            get {
                return ResourceManager.GetString("PhaseScatterWipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface check.
        /// </summary>
        public static string PhaseSurfaceCheck {
            get {
                return ResourceManager.GetString("PhaseSurfaceCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tail wipe.
        /// </summary>
        public static string PhaseTailWipe {
            get {
                return ResourceManager.GetString("PhaseTailWipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification.
        /// </summary>
        public static string PhaseVerification {
            get {
                return ResourceManager.GetString("PhaseVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed:.
        /// </summary>
        public static string ReportCompleted {
            get {
                return ResourceManager.GetString("ReportCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No — Interrupted.
        /// </summary>
        public static string ReportCompletedNo {
            get {
                return ResourceManager.GetString("ReportCompletedNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ReportCompletedYes {
            get {
                return ResourceManager.GetString("ReportCompletedYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverage:.
        /// </summary>
        public static string ReportCoverage {
            get {
                return ResourceManager.GetString("ReportCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string ReportDate {
            get {
                return ResourceManager.GetString("ReportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive:.
        /// </summary>
        public static string ReportDrive {
            get {
                return ResourceManager.GetString("ReportDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        public static string ReportDuration {
            get {
                return ResourceManager.GetString("ReportDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Sectors:.
        /// </summary>
        public static string ReportEmptySectors {
            get {
                return ResourceManager.GetString("ReportEmptySectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Method:.
        /// </summary>
        public static string ReportFillMethod {
            get {
                return ResourceManager.GetString("ReportFillMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO: {0}% of sampled sectors contain data (minimal)..
        /// </summary>
        public static string ReportInfoMinimalData {
            get {
                return ResourceManager.GetString("ReportInfoMinimalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Data Fill (single pass).
        /// </summary>
        public static string ReportMethodRandom {
            get {
                return ResourceManager.GetString("ReportMethodRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random + Zero Fill (two passes).
        /// </summary>
        public static string ReportMethodRandomZero {
            get {
                return ResourceManager.GetString("ReportMethodRandomZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero Fill (single pass).
        /// </summary>
        public static string ReportMethodZero {
            get {
                return ResourceManager.GetString("ReportMethodZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Wipe (every sector).
        /// </summary>
        public static string ReportModeFullDetail {
            get {
                return ResourceManager.GetString("ReportModeFullDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Wipe (head + tail + scatter).
        /// </summary>
        public static string ReportModeSmartDetail {
            get {
                return ResourceManager.GetString("ReportModeSmartDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: {0}% of sampled sectors contain data.
        ///    Recommend running a wipe before selling..
        /// </summary>
        public static string ReportNoteDataPresence {
            get {
                return ResourceManager.GetString("ReportNoteDataPresence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK: Drive appears to be clean — no data found in sampled sectors..
        /// </summary>
        public static string ReportOkClean {
            get {
                return ResourceManager.GetString("ReportOkClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK: No read errors detected. Drive surface appears healthy..
        /// </summary>
        public static string ReportOkNoErrors {
            get {
                return ResourceManager.GetString("ReportOkNoErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Errors:.
        /// </summary>
        public static string ReportReadErrors {
            get {
                return ResourceManager.GetString("ReportReadErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string ReportResults {
            get {
                return ResourceManager.GetString("ReportResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sectors Sampled:.
        /// </summary>
        public static string ReportSectorsSampled {
            get {
                return ResourceManager.GetString("ReportSectorsSampled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sectors w/ Data:.
        /// </summary>
        public static string ReportSectorsWithData {
            get {
                return ResourceManager.GetString("ReportSectorsWithData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sectors Written:.
        /// </summary>
        public static string ReportSectorsWritten {
            get {
                return ResourceManager.GetString("ReportSectorsWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial:.
        /// </summary>
        public static string ReportSerial {
            get {
                return ResourceManager.GetString("ReportSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        public static string ReportSize {
            get {
                return ResourceManager.GetString("ReportSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRIVEFLIP — SURFACE CHECK REPORT.
        /// </summary>
        public static string ReportSurfaceCheckTitle {
            get {
                return ResourceManager.GetString("ReportSurfaceCheckTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification:    {0} sectors failed verification.
        /// </summary>
        public static string ReportVerificationFailed {
            get {
                return ResourceManager.GetString("ReportVerificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification:    PASSED — all sectors verified clean.
        /// </summary>
        public static string ReportVerificationPassed {
            get {
                return ResourceManager.GetString("ReportVerificationPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Read errors detected. Drive may have bad sectors.
        ///    Consider replacing this drive before selling..
        /// </summary>
        public static string ReportWarnReadErrors {
            get {
                return ResourceManager.GetString("ReportWarnReadErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe Mode:.
        /// </summary>
        public static string ReportWipeMode {
            get {
                return ResourceManager.GetString("ReportWipeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK: Drive has been wiped successfully..
        /// </summary>
        public static string ReportWipeSuccess {
            get {
                return ResourceManager.GetString("ReportWipeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRIVEFLIP — WIPE REPORT.
        /// </summary>
        public static string ReportWipeTitle {
            get {
                return ResourceManager.GetString("ReportWipeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Wipe completed with errors. Some sectors may not have been overwritten..
        /// </summary>
        public static string ReportWipeWithErrors {
            get {
                return ResourceManager.GetString("ReportWipeWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Errors:.
        /// </summary>
        public static string ReportWriteErrors {
            get {
                return ResourceManager.GetString("ReportWriteErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revalidate.
        /// </summary>
        public static string Revalidate {
            get {
                return ResourceManager.GetString("Revalidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DO NOT SELL.
        /// </summary>
        public static string RiskDoNotSell {
            get {
                return ResourceManager.GetString("RiskDoNotSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOOD TO SELL.
        /// </summary>
        public static string RiskGoodToSell {
            get {
                return ResourceManager.GetString("RiskGoodToSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT ASSESSED.
        /// </summary>
        public static string RiskNotAssessed {
            get {
                return ResourceManager.GetString("RiskNotAssessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REVIEW NEEDED.
        /// </summary>
        public static string RiskReviewNeeded {
            get {
                return ResourceManager.GetString("RiskReviewNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Summary.
        /// </summary>
        public static string RiskSummaryLabel {
            get {
                return ResourceManager.GetString("RiskSummaryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNKNOWN.
        /// </summary>
        public static string RiskUnknown {
            get {
                return ResourceManager.GetString("RiskUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Check &amp; Wipe.
        /// </summary>
        public static string RunCheckAndWipe {
            get {
                return ResourceManager.GetString("RunCheckAndWipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Surface Check.
        /// </summary>
        public static string RunSurfaceCheck {
            get {
                return ResourceManager.GetString("RunSurfaceCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a drive to view details.
        /// </summary>
        public static string SelectDrivePlaceholder {
            get {
                return ResourceManager.GetString("SelectDrivePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string SettingAdvanced {
            get {
                return ResourceManager.GetString("SettingAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign drive letter after wipe.
        /// </summary>
        public static string SettingAssignLetter {
            get {
                return ResourceManager.GetString("SettingAssignLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After formatting, assigns the next available drive letter..
        /// </summary>
        public static string SettingAssignLetterTooltip {
            get {
                return ResourceManager.GetString("SettingAssignLetterTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display debug export button.
        /// </summary>
        public static string SettingDebugExport {
            get {
                return ResourceManager.GetString("SettingDebugExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the debug data export button in the drive details pane..
        /// </summary>
        public static string SettingDebugExportTooltip {
            get {
                return ResourceManager.GetString("SettingDebugExportTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head/tail wipe:.
        /// </summary>
        public static string SettingHeadTailWipe {
            get {
                return ResourceManager.GetString("SettingHeadTailWipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string SettingLanguage {
            get {
                return ResourceManager.GetString("SettingLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log level:.
        /// </summary>
        public static string SettingLogLevel {
            get {
                return ResourceManager.GetString("SettingLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how much detail is written to the log file. Lower levels produce more output..
        /// </summary>
        public static string SettingLogLevelTooltip {
            get {
                return ResourceManager.GetString("SettingLogLevelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passes:.
        /// </summary>
        public static string SettingPasses {
            get {
                return ResourceManager.GetString("SettingPasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect internal drives.
        /// </summary>
        public static string SettingProtectInternal {
            get {
                return ResourceManager.GetString("SettingProtectInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevents all non-removable (internal) drives from being selected for operations..
        /// </summary>
        public static string SettingProtectInternalTooltip {
            get {
                return ResourceManager.GetString("SettingProtectInternalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect system drive.
        /// </summary>
        public static string SettingProtectSystem {
            get {
                return ResourceManager.GetString("SettingProtectSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevents the system drive (C:) from being selected for operations..
        /// </summary>
        public static string SettingProtectSystemTooltip {
            get {
                return ResourceManager.GetString("SettingProtectSystemTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick format after wipe.
        /// </summary>
        public static string SettingQuickFormat {
            get {
                return ResourceManager.GetString("SettingQuickFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After a successful wipe, initializes the disk as GPT and creates a single NTFS partition..
        /// </summary>
        public static string SettingQuickFormatTooltip {
            get {
                return ResourceManager.GetString("SettingQuickFormatTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scatter wipe:.
        /// </summary>
        public static string SettingScatterWipe {
            get {
                return ResourceManager.GetString("SettingScatterWipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface check:.
        /// </summary>
        public static string SettingSurfaceCheck {
            get {
                return ResourceManager.GetString("SettingSurfaceCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMART Attributes.
        /// </summary>
        public static string SmartAttributes {
            get {
                return ResourceManager.GetString("SmartAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cur.
        /// </summary>
        public static string SmartHeaderCurrent {
            get {
                return ResourceManager.GetString("SmartHeaderCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string SmartHeaderId {
            get {
                return ResourceManager.GetString("SmartHeaderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        public static string SmartHeaderName {
            get {
                return ResourceManager.GetString("SmartHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Value.
        /// </summary>
        public static string SmartHeaderRaw {
            get {
                return ResourceManager.GetString("SmartHeaderRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thresh.
        /// </summary>
        public static string SmartHeaderThreshold {
            get {
                return ResourceManager.GetString("SmartHeaderThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worst.
        /// </summary>
        public static string SmartHeaderWorst {
            get {
                return ResourceManager.GetString("SmartHeaderWorst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw SMART attributes are not available for this drive..
        /// </summary>
        public static string SmartNotAvailable {
            get {
                return ResourceManager.GetString("SmartNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied — run as Administrator.
        /// </summary>
        public static string StatusAccessDenied {
            get {
                return ResourceManager.GetString("StatusAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string StatusCancelled {
            get {
                return ResourceManager.GetString("StatusCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling....
        /// </summary>
        public static string StatusCancelling {
            get {
                return ResourceManager.GetString("StatusCancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check &amp; Wipe cancelled..
        /// </summary>
        public static string StatusCheckWipeCancelled {
            get {
                return ResourceManager.GetString("StatusCheckWipeCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check &amp; Wipe complete..
        /// </summary>
        public static string StatusCheckWipeComplete {
            get {
                return ResourceManager.GetString("StatusCheckWipeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check &amp; Wipe stopped after surface check. Review results above..
        /// </summary>
        public static string StatusCheckWipeStopped {
            get {
                return ResourceManager.GetString("StatusCheckWipeStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data dump cancelled..
        /// </summary>
        public static string StatusDataDumpCancelled {
            get {
                return ResourceManager.GetString("StatusDataDumpCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data dumped to {0}.
        /// </summary>
        public static string StatusDataDumped {
            get {
                return ResourceManager.GetString("StatusDataDumped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting drives....
        /// </summary>
        public static string StatusDetectingDrives {
            get {
                return ResourceManager.GetString("StatusDetectingDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dumping data for Disk {0}....
        /// </summary>
        public static string StatusDumpingData {
            get {
                return ResourceManager.GetString("StatusDumpingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string StatusError {
            get {
                return ResourceManager.GetString("StatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error detecting drives: {0}.
        /// </summary>
        public static string StatusErrorDetecting {
            get {
                return ResourceManager.GetString("StatusErrorDetecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors found.
        /// </summary>
        public static string StatusErrorsFound {
            get {
                return ResourceManager.GetString("StatusErrorsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting....
        /// </summary>
        public static string StatusFormatting {
            get {
                return ResourceManager.GetString("StatusFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} drive(s). Querying health data....
        /// </summary>
        public static string StatusFoundDrivesQuerying {
            get {
                return ResourceManager.GetString("StatusFoundDrivesQuerying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} physical drive(s). Select drives and choose an action..
        /// </summary>
        public static string StatusFoundDrivesReady {
            get {
                return ResourceManager.GetString("StatusFoundDrivesReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthy.
        /// </summary>
        public static string StatusHealthy {
            get {
                return ResourceManager.GetString("StatusHealthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive listing copied to clipboard..
        /// </summary>
        public static string StatusListingCopied {
            get {
                return ResourceManager.GetString("StatusListingCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No non-system drives selected..
        /// </summary>
        public static string StatusNoSelection {
            get {
                return ResourceManager.GetString("StatusNoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase 1: Running surface check....
        /// </summary>
        public static string StatusPhase1 {
            get {
                return ResourceManager.GetString("StatusPhase1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase 2: Wiping drives....
        /// </summary>
        public static string StatusPhase2 {
            get {
                return ResourceManager.GetString("StatusPhase2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query failed.
        /// </summary>
        public static string StatusQueryFailed {
            get {
                return ResourceManager.GetString("StatusQueryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select drives and choose an action..
        /// </summary>
        public static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running surface check....
        /// </summary>
        public static string StatusRunningSurfaceCheck {
            get {
                return ResourceManager.GetString("StatusRunningSurfaceCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMART query failed for Disk {0}: {1}.
        /// </summary>
        public static string StatusSmartQueryFailed {
            get {
                return ResourceManager.GetString("StatusSmartQueryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface check complete..
        /// </summary>
        public static string StatusSurfaceCheckComplete {
            get {
                return ResourceManager.GetString("StatusSurfaceCheckComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe operation complete..
        /// </summary>
        public static string StatusWipeComplete {
            get {
                return ResourceManager.GetString("StatusWipeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe complete.
        /// </summary>
        public static string StatusWipeCompleteShort {
            get {
                return ResourceManager.GetString("StatusWipeCompleteShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe complete — format failed: {0}.
        /// </summary>
        public static string StatusWipeFormatFailed {
            get {
                return ResourceManager.GetString("StatusWipeFormatFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe complete — formatted as {0}.
        /// </summary>
        public static string StatusWipeFormatted {
            get {
                return ResourceManager.GetString("StatusWipeFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe incomplete.
        /// </summary>
        public static string StatusWipeIncomplete {
            get {
                return ResourceManager.GetString("StatusWipeIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiping drives....
        /// </summary>
        public static string StatusWipingDrives {
            get {
                return ResourceManager.GetString("StatusWipingDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Check.
        /// </summary>
        public static string SurfaceCheck {
            get {
                return ResourceManager.GetString("SurfaceCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-only test that samples random sectors to detect read errors and data presence..
        /// </summary>
        public static string SurfaceCheckDesc {
            get {
                return ResourceManager.GetString("SurfaceCheckDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Remaining.
        /// </summary>
        public static string TimeRemaining {
            get {
                return ResourceManager.GetString("TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string TooltipAbout {
            get {
                return ResourceManager.GetString("TooltipAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TooltipSettings {
            get {
                return ResourceManager.GetString("TooltipSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase text size (Ctrl++).
        /// </summary>
        public static string TooltipZoomIn {
            get {
                return ResourceManager.GetString("TooltipZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease text size (Ctrl+-).
        /// </summary>
        public static string TooltipZoomOut {
            get {
                return ResourceManager.GetString("TooltipZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset text size.
        /// </summary>
        public static string TooltipZoomReset {
            get {
                return ResourceManager.GetString("TooltipZoomReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveFlip — Surface Check &amp; Drive Prep.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe.
        /// </summary>
        public static string Wipe {
            get {
                return ResourceManager.GetString("Wipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanently destroys all data by overwriting drive sectors..
        /// </summary>
        public static string WipeDesc {
            get {
                return ResourceManager.GetString("WipeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        public static string WipeMethodLabel {
            get {
                return ResourceManager.GetString("WipeMethodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Fill.
        /// </summary>
        public static string WipeMethodRandomFill {
            get {
                return ResourceManager.GetString("WipeMethodRandomFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random + Zero.
        /// </summary>
        public static string WipeMethodRandomZero {
            get {
                return ResourceManager.GetString("WipeMethodRandomZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero Fill.
        /// </summary>
        public static string WipeMethodZeroFill {
            get {
                return ResourceManager.GetString("WipeMethodZeroFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Wipe.
        /// </summary>
        public static string WipeModeFullWipe {
            get {
                return ResourceManager.GetString("WipeModeFullWipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string WipeModeLabel {
            get {
                return ResourceManager.GetString("WipeModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Wipe.
        /// </summary>
        public static string WipeModeSmartWipe {
            get {
                return ResourceManager.GetString("WipeModeSmartWipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe Selected Drives.
        /// </summary>
        public static string WipeSelectedDrives {
            get {
                return ResourceManager.GetString("WipeSelectedDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify after wipe.
        /// </summary>
        public static string WipeVerifyLabel {
            get {
                return ResourceManager.GetString("WipeVerifyLabel", resourceCulture);
            }
        }
    }
}
